language: ruby
os: linux
dist: focal
cache:
  bundler: true
  yarn: true

bundler_args: --without production

addons:
  postgresql: "12"
  apt:
    packages:
    - postgresql-12
    - postgresql-client-12
env:
  global:
  - PGPORT=5433
  - PGUSER=travis

before install:
  - bundle config set --local path ${BUNDLE_PATH:-vendor/bundle}
  - bundle config set --local without 'production'

before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database travis_ci_test;' -U travis
  - nvm install 18.6
  - nvm list
  - nvm alias default 18
  - node --version
  - npm --version
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.19  
  - export PATH="$HOME/.yarn/bin:$PATH"
  - bin/rails javascript:install:esbuild
  - bin/setup

script:
  - bin/rubocop
  - bin/rails test:system

# safelist
branches:
  only:
  - main

notifications:
  email: "snepote@gmail.com"