language: ruby
os: linux
dist: focal
cache:
  bundler: true
  yarn: true

bundler_args: --without production

services:
  - postgresql

before_script:
  - sudo apt update
  - sudo apt install nodejs
  - node --version
  - npm install -g 8.12.1
  - npm --version  
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.19  
  - export PATH="$HOME/.yarn/bin:$PATH"
  - bin/rails javascript:install:esbuild --Yes
  - bin/rails css:install:sass --Yes
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - bin/setup

script:
  - bin/rails test:system

# safelist
branches:
  only:
  - main

notifications:
  email: "snepote@gmail.com"