language: ruby
cache: bundler

bundler_args: --without production

services:
  - postgresql

before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - bin/setup

script:
  - bin/rails test:system

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

# safelist
branches:
  only:
  - main

notifications:
  email: "snepote@gmail.com"