language: ruby
os: linux
dist: xenial
cache:
  bundler: true
  yarn: true

bundler_args: --without production

services:
  - postgresql

before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.19  
  - export PATH="$HOME/.yarn/bin:$PATH"
  - bin/rails javascript:install:esbuild
  - bin/rails css:install:sass
  - yarn build
  - yarn build:css  
  - bin/setup

script:
  - bin/rails test:system

# safelist
branches:
  only:
  - main

notifications:
  email: "snepote@gmail.com"