language: ruby
cache: bundler
  bundler: true
  yarn: true

bundler_args: --without production

services:
  - postgresql

before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.19
  - export PATH="$HOME/.yarn/bin:$PATH"  
  - bin/setup

script:
  - bin/rails test:system

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

# safelist
branches:
  only:
  - main

notifications:
  email: "snepote@gmail.com"